---
Title :"Reproducible Research Week 2 Course Project 1"
output: html_document
date: "2022-11-25"
By : G.JEEVARATHINAM
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Introduction

#It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as a Fitbit, Nike Fuelband, or Jawbone Up. These type of devices are part of the “quantified self” movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. But these data remain under-utilized both because the raw data are hard to obtain and there is a lack of statistical methods and software for processing and interpreting the data.

#This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

#The data for this assignment can be downloaded from the course web site:
  
# Dataset: Activity monitoring data [52K] The variables included in this dataset are:
# steps: Number of steps taking in a 5-minute interval (missing values are coded as NA) date: The date on which the measurement was taken in YYYY-MM-DD format interval: Identifier for the 5-minute interval in which measurement was taken The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset.

#Load Libraries
library(ggplot2)

## Attaching package: 'dplyr'
library(dplyr)

## Loading and preprocessing the data.

activity<-read.csv("C:/users/sowba/downloads/Reproducible_Research_Dataset/repdata_data_activity/activity.csv")
activity$date<-as.Date(activity$date)

#ANALYSIS

#a.Calculate the total number of steps

stepsPerDay<-activity%>%
  group_by(date) %>%
  summarize(sumsteps=sum(steps,na.rm=TRUE))
#Display first 10 rows of data
head(stepsPerDay,10)
#stepsPerDay
```

```{r plot}
#b.Make a histogram of the total number of steps taken each day
hist(stepsPerDay$sumsteps,main="Histogram of Daily Steps",
     col="blue",xlab="Steps",ylim=c(0,30))
```

```{r}
#c.Calculate and report the mean and median of the total number of steps taken per day

meanPreNA <- round(mean(stepsPerDay$sumsteps),digits = 2)
medianPreNA <- round(median(stepsPerDay$sumsteps),digits = 2)
```

```{r}
print(paste("The mean is: ", meanPreNA))
```

```{r}
print(paste("The median is: ", medianPreNA))
```

#What is the average daily activity pattern? \# Make a time series plot (i.e. type = "l"\|) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis).

stepsPerInterval \<- activity %\>% group_by(interval) %\>% summarize(meansteps = mean(steps, na.rm = TRUE)) #Display first 10 rows of data

```{r}
head(stepsPerInterval,10)
```

```{r plot}
plot(stepsPerInterval$meansteps ~ stepsPerInterval$interval,
     col="blue", type="l", xlab = "5 Minute Intervals", ylab = "Average Number of Steps",
     main = "Steps By Time Interval")
```

```{r}
#2.Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
print(paste("Interval containing the most steps on average: ",stepsPerInterval$interval[which.max(stepsPerInterval$meansteps)]))
```

```{r}
print(paste("Average steps for that interval: ",round(max(stepsPerInterval$meansteps),digits=2)))

```

```{r}
#Imputing missing values
#1.Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

print(paste("The total number of rows with NA is: ",sum(is.na(activity$steps))))
```

```{r}
#2.Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
#NA Strategy - To solve for the missing NA values the average for the associated interval will be used. The average was built in a prior step and is readily available: First, loop through all records of a copy of the ‘activity’ data. Then, look for records containing NA values. Finally, transform the ‘steps’ value based on matching the interval in the ‘stepsPerInterval’ data frame created in a prior step.

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
#Before 
#Display first 10 rows of data
```

```{r}
head(activity,10)
```

```{r}
activityNoNA <- activity  
for (i in 1:nrow(activity)){
  if(is.na(activity$steps[i])){
    activityNoNA$steps[i]<- stepsPerInterval$meansteps[activityNoNA$interval[i] == stepsPerInterval$interval]
  }
}

#After
#Display first 10 rows of data

```

```{r}
head(activityNoNA,10)
```

```{r}

#4.Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

  stepsPerDay <- activityNoNA %>%
  group_by(date) %>%
  summarize(sumsteps = sum(steps, na.rm = TRUE)) 
```

```{r}
  head(stepsPerDay,10)
```

```{r plot}
  hist(stepsPerDay$sumsteps, main = "Histogram of Daily Steps", 
       col="pink", xlab="Steps")
```

```{r}
  meanPostNA <- round(mean(stepsPerDay$sumsteps), digits = 2)
  medianPostNA <- round(median(stepsPerDay$sumsteps), digits = 2)
  print(paste("The mean is: ", mean(meanPostNA)))
  ## [1] "The mean is:  10766.19"
```

```{r}
  print(paste("The median is: ", median(medianPostNA)))
## [1] "The median is:  10766.19"
```

```{r}
  #Once logic is applied to imput missing values it allows for all detail records to be included increasing both the mean and median. The mean increases from 9354.23 to 10766.19. It is important to note that NA values in the first part of the project were ignored (na.rm = TRUE). Once averages were applied to the missing values the overall mean increased.
 
  NACompare <- data.frame(mean = c(meanPreNA,meanPostNA),median = c(medianPreNA,medianPostNA))
  rownames(NACompare) <- c("Pre NA Transformation", "Post NA Transformation")
```

```{r}
    print(NACompare)
  ##                            mean   median
  ## Pre NA Transformation   9354.23 10395.00
  ## Post NA Transformation 10766.19 10766.19
#  Are there differences in activity patterns between weekdays and weekends?
 #  1. Create a new factor variable in the dataset with two levels - “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
  activityDoW <- activityNoNA
  activityDoW$date <- as.Date(activityDoW$date)
  activityDoW$day <- ifelse(weekdays(activityDoW$date) %in% c("Saturday", "Sunday"), "weekend", "weekday")
  activityDoW$day <- as.factor(activityDoW$day)

    #2. Make a panel plot containing a time series plot (i.e. type=“l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).
  activityWeekday <- filter(activityDoW, activityDoW$day == "weekday")
  activityWeekend <- filter(activityDoW, activityDoW$day == "weekend")
  
  activityWeekday <- activityWeekday %>%
    group_by(interval) %>%
    summarize(steps = mean(steps)) 
  activityWeekday$day <- "weekday"
  
  activityWeekend <- activityWeekend %>%
    group_by(interval) %>%
    summarize(steps = mean(steps)) 
  activityWeekend$day <- "weekend"
  
  wkdayWkend <- rbind(activityWeekday, activityWeekend)
  wkdayWkend$day <- as.factor(wkdayWkend$day)
```

```{r plot}
      g <- ggplot (wkdayWkend, aes (interval, steps))
    g + geom_line() + facet_grid (day~.) + 
    theme(axis.text = element_text(size = 12),axis.title 
    = element_text(size = 14)) + labs(y = "Number of Steps") + 
    labs(x = "Interval") + ggtitle("Average Number of Steps - 
    Weekday vs. Weekend") + theme(plot.title = element_text(hjust = 0.5))
```

```{r}
  #The chart shows slight differences in the step patterns throughout the average daily intervals. For weekdays there is a larger spike in the morning intervals that could indicate commuters on their way to work. Spikes during the late morning and early afternoon seem to be higher on the weekends. One can assume that this might be related to subjects running errands, doing yardwork, exercising, etc. Those same intervals for weekdays appear to be less perhaps due to subjects sitting at their desk, driving a truck or standing in front of a machine in a factory.
  
```
